import os
import re
import urllib.request

SUBMISSION_REPO = "turingmotors/hrf-with-cosmos-reason2"
SUBMISSION_BRANCH = "main"
SOURCE_MD_PATH = "project_features.md"

RAW_BASE = f"https://raw.githubusercontent.com/{SUBMISSION_REPO}/{SUBMISSION_BRANCH}"
BLOB_BASE = f"https://github.com/{SUBMISSION_REPO}/blob/{SUBMISSION_BRANCH}"


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def normalize_for_mkdocs(md: str) -> str:
    """
    GitHub(GFM)では“それっぽく”表示されても、MkDocs(Python-Markdown)では
    表や箇条書きが崩れる「改行不足/1行化」を最低限補正する。
    """
    md = md.replace("\r\n", "\n").replace("\r", "\n")

    # (A) 見出しの前に空行を入れる（### を壊さない）
    # 先頭または空白の後に "#... " が来たら、前を段落区切りにする
    md = re.sub(r"(^|\s)(#{1,6})\s+", r"\n\n\2 ", md)

    # (B) コロン直後の箇条書きが潰れているのを分離
    # 例: "...: - foo - bar" -> "...:\n\n- foo\n- bar"
    md = re.sub(r":\s+-\s+", ":\n\n- ", md)

    # (C) テーブル行が 1 行に潰れているのを分離
    # よくある: "| a | b | | --- | --- | | x | y |"
    md = md.replace(" | |", "\n|")

    # テーブル開始が文中に埋まっているケース（例: "Example: | A | B |"）
    md = re.sub(r"([:.])\s+\|", r"\1\n\n|", md)

    # (D) 箇条書きが文中に潰れているのを分離（- の前に改行）
    # ただし数式等を壊しにくいよう「スペース + - + スペース」を対象にする
    md = re.sub(r"\s+-\s+", r"\n- ", md)

    # (E) 余計な行末スペースを削除
    md = re.sub(r"[ \t]+\n", "\n", md)

    return md


def patch_image_placeholders(md: str) -> str:
    """
    元の project_features.md に残っている "" 等のプレースホルダを
    実在する画像(GIF)の Markdown に置換する。
    """
    # 100_app (Web Application)
    md = md.replace(
        "### Web Application ([100_app](./100_app/)) ",
        "### Web Application ([100_app](./100_app/))\n\n"
        f"![]({RAW_BASE}/100_app/assets/app_sample_4x.gif)\n",
    )

    # 005_2coool-studio (Blind A/B Testing Tool)
    md = md.replace(
        "### Blind A/B Testing Tool ([005_2coool-studio](./005_2coool-studio/)) ",
        "### Blind A/B Testing Tool ([005_2coool-studio](./005_2coool-studio/))\n\n"
        f"![]({RAW_BASE}/005_2coool-studio/assets/2coool-studio_sample_light.gif)\n",
    )

    return md


def rewrite_relative_links(md: str) -> str:
    """
    - Images: ![alt](relative.png) -> RAW_BASE/relative.png
    - Links:  [text](relative.md)  -> BLOB_BASE/relative.md
    keep absolute URLs (http/https), anchors (#...), mailto untouched
    """
    def is_relative(url: str) -> bool:
        return (
            not re.match(r"^(https?:)?//", url)
            and not url.startswith("#")
            and not url.startswith("mailto:")
        )

    # Images: ![...](...)
    def repl_img(m):
        alt, url = m.group(1), m.group(2).strip()
        if is_relative(url):
            url = f"{RAW_BASE}/{url.lstrip('./')}"
        return f"![{alt}]({url})"

    md = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", repl_img, md)

    # Links (exclude images): [...](...)
    def repl_link(m):
        text, url = m.group(1), m.group(2).strip()
        if is_relative(url):
            url = f"{BLOB_BASE}/{url.lstrip('./')}"
        return f"[{text}]({url})"

    md = re.sub(r"(?<!\!)\[([^\]]+)\]\(([^)]+)\)", repl_link, md)
    return md


def main():
    src_url = f"{RAW_BASE}/{SOURCE_MD_PATH}"
    md = fetch_text(src_url)

    # 1) MkDocs向けに改行整形
    md = normalize_for_mkdocs(md)

    # 2) 画像プレースホルダを実画像へ
    md = patch_image_placeholders(md)

    # 3) 相対リンクを GitHub / raw に変換
    md = rewrite_relative_links(md)

    header = f"""<!--
AUTO-GENERATED.
Source: {BLOB_BASE}/{SOURCE_MD_PATH}
Do not edit this file directly.
-->

"""
    out = header + md

    os.makedirs("docs", exist_ok=True)
    with open("docs/index.md", "w", encoding="utf-8") as f:
        f.write(out)

    print("Wrote docs/index.md from", src_url)


if __name__ == "__main__":
    main()
