import os
import re
import urllib.request

SUBMISSION_REPO = "turingmotors/hrf-with-cosmos-reason2"
SUBMISSION_BRANCH = "main"
SOURCE_MD_PATH = "project_features.md"

RAW_BASE = f"https://raw.githubusercontent.com/{SUBMISSION_REPO}/{SUBMISSION_BRANCH}"
BLOB_BASE = f"https://github.com/{SUBMISSION_REPO}/blob/{SUBMISSION_BRANCH}"


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def normalize_for_mkdocs(md: str) -> str:
    """
    GFMでは“それっぽく”表示されるが、MkDocs(Python-Markdown)では崩れる
    「1行に潰れたMarkdown」を、最低限 “改行のあるMarkdown” に整形する。

    重点:
      - 見出し(#, ##, ### ...)の前に必ず改行を入れる（###を壊さない）
      - 1行テーブルを 行ごとに改行してテーブルとして成立させる
      - コロン後の箇条書きも改行して箇条書きとして成立させる
    """
    md = md.replace("\r\n", "\n").replace("\r", "\n")

    # (A) 見出しを壊さずに分離する
    # 先頭 or 空白の後に来る "#... " を、前に空行を入れて行頭に寄せる
    # 例: " ... ## Title ..." -> "\n\n## Title ..."
    md = re.sub(r"(^|\s)(#{1,6})\s+", r"\n\n\2 ", md)

    # (B) 「: - 」で始まる“潰れた箇条書き”を分離
    # 例: "**Real-world applications**: - **Autonomous** ..." -> "...\n\n- **Autonomous** ..."
    md = re.sub(r":\s+-\s+", ":\n\n- ", md)

    # (C) テーブルを成立させる：行頭の "| " を行頭に置く
    # 元は "...: | A | B | |---|---| | x | y | ..." のように 1行に潰れている。
    # ルール: " | |" という“行の境界”を、改行 + "|" に変える。
    md = md.replace(" | |", "\n|")

    # さらに「テーブル開始」が文中にある場合に備えて、
    # ": |" または ". |" の後の "| ..." を改行してテーブル開始扱いにする
    md = re.sub(r"([:.])\s+\|", r"\1\n\n|", md)

    # (D) 箇条書きが文中に潰れているのを分離（- ** 以外も拾う）
    md = re.sub(r"\s+-\s+", r"\n- ", md)

    # (E) 余計な行末スペース除去
    md = re.sub(r"[ \t]+\n", "\n", md)

    return md


def rewrite_relative_links(md: str) -> str:
    """
    - Images: ![alt](relative.png) -> RAW_BASE/relative.png
    - Links:  [text](relative.md)  -> BLOB_BASE/relative.md
    """
    def is_relative(url: str) -> bool:
        return (
            not re.match(r"^(https?:)?//", url)
            and not url.startswith("#")
            and not url.startswith("mailto:")
        )

    def repl_img(m):
        alt, url = m.group(1), m.group(2).strip()
        if is_relative(url):
            url = f"{RAW_BASE}/{url.lstrip('./')}"
        return f"![{alt}]({url})"

    md = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", repl_img, md)

    def repl_link(m):
        text, url = m.group(1), m.group(2).strip()
        if is_relative(url):
            url = f"{BLOB_BASE}/{url.lstrip('./')}"
        return f"[{text}]({url})"

    md = re.sub(r"(?<!\!)\[([^\]]+)\]\(([^)]+)\)", repl_link, md)
    return md


def main():
    src_url = f"{RAW_BASE}/{SOURCE_MD_PATH}"
    md = fetch_text(src_url)

    md = normalize_for_mkdocs(md)
    md = rewrite_relative_links(md)

    header = f"""<!--
AUTO-GENERATED.
Source: {BLOB_BASE}/{SOURCE_MD_PATH}
Do not edit this file directly.
-->

"""
    out = header + md

    os.makedirs("docs", exist_ok=True)
    with open("docs/index.md", "w", encoding="utf-8") as f:
        f.write(out)

    print("Wrote docs/index.md from", src_url)


if __name__ == "__main__":
    main()
