import os
import re
import urllib.request

SUBMISSION_REPO = "turingmotors/hrf-with-cosmos-reason2"
SUBMISSION_BRANCH = "main"
SOURCE_MD_PATH = "project_features.md"

RAW_BASE = f"https://raw.githubusercontent.com/{SUBMISSION_REPO}/{SUBMISSION_BRANCH}"
BLOB_BASE = f"https://github.com/{SUBMISSION_REPO}/blob/{SUBMISSION_BRANCH}"

def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")

def normalize_for_mkdocs(md: str) -> str:
    md = md.replace("\r\n", "\n").replace("\r", "\n")
    md = re.sub(r"(^|\s)(#{1,6})\s+", r"\n\n\2 ", md)
    md = re.sub(r":\s+-\s+", ":\n\n- ", md)
    md = md.replace(" | |", "\n|")
    md = re.sub(r"([:.])\s+\|", r"\1\n\n|", md)
    md = re.sub(r"\s+-\s+", r"\n- ", md)
    md = re.sub(r"[ \t]+\n", "\n", md)
    return md

def patch_image_placeholders(md: str) -> str:
    md = md.replace(
        "### Web Application ([100_app](./100_app/)) ",
        "### Web Application ([100_app](./100_app/))\n\n"
        f"![]({RAW_BASE}/100_app/assets/app_sample_4x.gif)\n",
    )
    md = md.replace(
        "### Blind A/B Testing Tool ([005_2coool-studio](./005_2coool-studio/)) ",
        "### Blind A/B Testing Tool ([005_2coool-studio](./005_2coool-studio/))\n\n"
        f"![]({RAW_BASE}/005_2coool-studio/assets/2coool-studio_sample_light.gif)\n",
    )
    return md

def rewrite_relative_links(md: str) -> str:
    def is_relative(url: str) -> bool:
        return (
            not re.match(r"^(https?:)?//", url)
            and not url.startswith("#")
            and not url.startswith("mailto:")
        )

    def repl_img(m):
        alt, url = m.group(1), m.group(2).strip()
        if is_relative(url):
            url = f"{RAW_BASE}/{url.lstrip('./')}"
        return f"![{alt}]({url})"

    md = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", repl_img, md)

    def repl_link(m):
        text, url = m.group(1), m.group(2).strip()
        if is_relative(url):
            url = f"{BLOB_BASE}/{url.lstrip('./')}"
        return f"[{text}]({url})"

    md = re.sub(r"(?<!\!)\[([^\]]+)\]\(([^)]+)\)", repl_link, md)
    return md

def main():
    src_url = f"{RAW_BASE}/{SOURCE_MD_PATH}"
    md = fetch_text(src_url)
    md = normalize_for_mkdocs(md)
    md = patch_image_placeholders(md)
    md = rewrite_relative_links(md)

    header = f"""<!--
AUTO-GENERATED.
Source: {BLOB_BASE}/{SOURCE_MD_PATH}
Do not edit this file directly.
-->

"""
    out = header + md
    os.makedirs("docs", exist_ok=True)
    with open("docs/index.md", "w", encoding="utf-8") as f:
        f.write(out)

if __name__ == "__main__":
    main()
